#ifndef THREADS_H
#define THREADS_H (1)

#include "cmsis_os.h"

#define HEARTBEAT_PERIOD_MS 500u
#define MOTOR_CONTROLS_PERIOD_MS 25u
#define SERIAL_LOGGER_PERIOD_MS 10u

#define HEARTBEAT_STACK_SIZE_WORDS 256u
#define MOTOR_CONTROLS_STACK_SIZE_WORDS 256u
#define SERIAL_LOGGER_STACK_SIZE_WORDS 256u

#define HEARTBEAT_PRIORITY osPriorityLow
#define MOTOR_CONTROLS_PRIORITY osPriorityRealtime
#define SERIAL_LOGGER_PRIORITY osPriorityNormal

#endif  // THREADS_H
