#ifndef IO_H
#define IO_H (1)

#include "stm32f4xx_hal.h"

#define IMU_INT_PIN GPIO_PIN_13
#define IMU_INT_GPIO_PORT GPIOC

#define HSE_IN_PIN GPIO_PIN_0
#define HSE_IN_GPIO_PORT GPIOH

#define HSE_OUT_PIN GPIO_PIN_1
#define HSE_OUT_GPIO_PORT GPIOH

#define HEARTBEAT_LED_PIN GPIO_PIN_2
#define HEARTBEAT_LED_GPIO_PORT GPIOC

#define D1_AIN1_PIN GPIO_PIN_3
#define D1_AIN1_GPIO_PORT GPIOC

#define D1_MOTORA_CHA_PIN GPIO_PIN_0
#define D1_MOTORA_CHA_GPIO_PORT GPIOA

#define D1_MOTORA_CHB_PIN GPIO_PIN_1
#define D1_MOTORA_CHB_GPIO_PORT GPIOA

#define D1_PWMA_PIN GPIO_PIN_2
#define D1_PWMA_GPIO_PORT GPIOA

#define D1_PWMB_PIN GPIO_PIN_3
#define D1_PWMB_GPIO_PORT GPIOA

#define D1_AIN2_PIN GPIO_PIN_4
#define D1_AIN2_GPIO_PORT GPIOA

#define VBATT_AIN_PIN GPIO_PIN_5
#define VBATT_AIN_GPIO_PORT GPIOA

#define D1_MOTORB_CHA_PIN GPIO_PIN_6
#define D1_MOTORB_CHA_GPIO_PORT GPIOA

#define D1_MOTORB_CHB_PIN GPIO_PIN_7
#define D1_MOTORB_CHB_GPIO_PORT GPIOA

#define D1_BIN1_PIN GPIO_PIN_4
#define D1_BIN1_GPIO_PORT GPIOC

#define D1_BIN2_PIN GPIO_PIN_5
#define D1_BIN2_GPIO_PORT GPIOC

#define D1_STBY_PIN GPIO_PIN_0
#define D1_STBY_GPIO_PORT GPIOB

#define D2_AIN1_PIN GPIO_PIN_1
#define D2_AIN1_GPIO_PORT GPIOB

#define D2_AIN2_PIN GPIO_PIN_2
#define D2_AIN2_GPIO_PORT GPIOB

#define CAN2_RS_PIN GPIO_PIN_10
#define CAN2_RS_GPIO_PORT GPIOB

#define D2_PWMA_PIN GPIO_PIN_14
#define D2_PWMA_GPIO_PORT GPIOB

#define D2_PWMB_PIN GPIO_PIN_15
#define D2_PWMB_GPIO_PORT GPIOB

#define D2_MOTORA_CHA_PIN GPIO_PIN_6
#define D2_MOTORA_CHA_GPIO_PORT GPIOC

#define D2_MOTORA_CHB_PIN GPIO_PIN_7
#define D2_MOTORA_CHB_GPIO_PORT GPIOC

#define D2_BIN2_PIN GPIO_PIN_8
#define D2_BIN2_GPIO_PORT GPIOC

#define D2_BIN1_PIN GPIO_PIN_9
#define D2_BIN1_GPIO_PORT GPIOC

#define D2_MOTORB_CHA_PIN GPIO_PIN_8
#define D2_MOTORB_CHA_GPIO_PORT GPIOA

#define D2_MOTORB_CHB_PIN GPIO_PIN_9
#define D2_MOTORB_CHB_GPIO_PORT GPIOA

#define D2_STBY_PIN GPIO_PIN_10
#define D2_STBY_GPIO_PORT GPIOA

#define RF_SCK_PIN GPIO_PIN_10
#define RF_SCK_GPIO_PORT GPIOC

#define RF_MISO_PIN GPIO_PIN_11
#define RF_MISO_GPIO_PORT GPIOC

#define RF_MOSI_PIN GPIO_PIN_12
#define RF_MOSI_GPIO_PORT GPIOC

#define RF_CS_PIN GPIO_PIN_2
#define RF_CS_GPIO_PORT GPIOD

#define RF_IRQ_PIN GPIO_PIN_4
#define RF_IRQ_GPIO_PORT GPIOB

#define RF_EN_PIN GPIO_PIN_5
#define RF_EN_GPIO_PORT GPIOB

#define DEBUG_TX_PIN GPIO_PIN_6
#define DEBUG_TX_GPIO_PORT GPIOB

#define DEBUG_RX_PIN GPIO_PIN_7
#define DEBUG_RX_GPIO_PORT GPIOB

#define IMU_SCL_PIN GPIO_PIN_8
#define IMU_SCL_GPIO_PORT GPIOB

#define IMU_SDA_PIN GPIO_PIN_9
#define IMU_SDA_GPIO_PORT GPIOB

#endif // IO_H
