#ifndef THREADS_H
#define THREADS_H (1)

#include "cmsis_os.h"

#define HEARTBEAT_PERIOD_MS 500u
#define SERIAL_LOGGER_PERIOD_MS 10u
#define RF_INTERFACE_PERIOD_MS 10u
#define IMU_INTERFACE_PERIOD_MS 10u
#define MOTOR_CONTROLS_PERIOD_MS 25u

// Delays used to de-sync thread timing
#define SERIAL_LOGGER_POST_INIT_DELAY_MS 2u
#define RF_INTERFACE_POST_INIT_DELAY_MS 6u
#define IMU_INTERFACE_POST_INIT_DELAY_MS 4u

#define HEARTBEAT_STACK_SIZE_WORDS 256u
#define SERIAL_LOGGER_STACK_SIZE_WORDS 256u
#define RF_INTERFACE_STACK_SIZE_WORDS 256u
#define IMU_INTERFACE_STACK_SIZE_WORDS 256u
#define MOTOR_CONTROLS_STACK_SIZE_WORDS 256u

#define HEARTBEAT_PRIORITY osPriorityLow
#define SERIAL_LOGGER_PRIORITY osPriorityBelowNormal
#define RF_INTERFACE_PRIORITY osPriorityNormal
#define IMU_INTERFACE_PRIORITY osPriorityAboveNormal
#define MOTOR_CONTROLS_PRIORITY osPriorityRealtime

#endif  // THREADS_H
